In [1]:
#import numpy library(np - alias) 
import numpy as np

In [2]:
#we can access the attribute by using np.<tab>
np.

SyntaxError: invalid syntax (<ipython-input-2-2ea14adf7083>, line 2)

In [ ]:
np?

In [ ]:
#create the one dim array by using list
arr1 = np.array([34,54,45])

In [ ]:
#(arr1) is the variable , and the output of arr1 is 1dim
arr1

In [ ]:
#next create the multidimensional array, here list is nested  
arr2 = np.array([[23,4,34],['re','we',53],[45,6,67]])

In [ ]:
arr2

In [ ]:
#ndim shows the dimensional of the array
arr2.ndim

In [ ]:
#we create the range value,[arange = start value,end value-1]
arr3 = np.arange(0,25)

In [ ]:
#it is single dim array
arr3

In [ ]:
#then we converted the single to multi dim array by using reshape attri,
temp1 = arr3.reshape(5,5)

In [ ]:
temp1

In [ ]:
#for to check the dim of the array by using attribute shape
temp1.shape

In [ ]:
#arr4 = np.array(range(i,i+3) for i in [2,3,6])

In [ ]:
i = input("enter the value:")

In [ ]:
i

In [ ]:
arr4 = np.array(range(i,i+3) for i in [2,3,6])




In [ ]:
arr4


In [6]:
#here changing the integer to float
arr5 = np.array([1,2,34,5,4], dtype='float32')

In [7]:
arr5

array([ 1.,  2., 34.,  5.,  4.], dtype=float32)

In [19]:
#arange shows the value from 0 to 25-1 = 24
arr5 = np.arange(0,25)

In [21]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr5.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
#linspace attri in numpy is same space bw number

arr6 = np.linspace(0,40)# 0 is start and 40 is end 

In [32]:
arr6

array([ 0.        ,  0.81632653,  1.63265306,  2.44897959,  3.26530612,
        4.08163265,  4.89795918,  5.71428571,  6.53061224,  7.34693878,
        8.16326531,  8.97959184,  9.79591837, 10.6122449 , 11.42857143,
       12.24489796, 13.06122449, 13.87755102, 14.69387755, 15.51020408,
       16.32653061, 17.14285714, 17.95918367, 18.7755102 , 19.59183673,
       20.40816327, 21.2244898 , 22.04081633, 22.85714286, 23.67346939,
       24.48979592, 25.30612245, 26.12244898, 26.93877551, 27.75510204,
       28.57142857, 29.3877551 , 30.20408163, 31.02040816, 31.83673469,
       32.65306122, 33.46938776, 34.28571429, 35.10204082, 35.91836735,
       36.73469388, 37.55102041, 38.36734694, 39.18367347, 40.        ])

In [37]:
# random number is generate the random value upto 50, this is in single dim array
arr6 = np.random.rand(50)

In [38]:
arr6

array([0.57117972, 0.29712764, 0.63574935, 0.09604288, 0.24959567,
       0.84610468, 0.07770735, 0.43963079, 0.24577761, 0.59276763,
       0.38071722, 0.25739061, 0.59199331, 0.38630943, 0.42199441,
       0.72241178, 0.2498922 , 0.98005639, 0.94802171, 0.16190527,
       0.71667415, 0.41881651, 0.14722644, 0.68723011, 0.97296211,
       0.18699003, 0.48769396, 0.04695431, 0.64542661, 0.34737254,
       0.94662015, 0.54126859, 0.11476384, 0.93481717, 0.8578775 ,
       0.33424679, 0.1003661 , 0.79871648, 0.38538724, 0.95570274,
       0.25572254, 0.86680446, 0.1426787 , 0.16278871, 0.66711765,
       0.8612611 , 0.60953081, 0.44476248, 0.88168337, 0.14968376])

In [41]:
#above array is converted into multi dim aray
arr6.reshape(10,5)

array([[0.57117972, 0.29712764, 0.63574935, 0.09604288, 0.24959567],
       [0.84610468, 0.07770735, 0.43963079, 0.24577761, 0.59276763],
       [0.38071722, 0.25739061, 0.59199331, 0.38630943, 0.42199441],
       [0.72241178, 0.2498922 , 0.98005639, 0.94802171, 0.16190527],
       [0.71667415, 0.41881651, 0.14722644, 0.68723011, 0.97296211],
       [0.18699003, 0.48769396, 0.04695431, 0.64542661, 0.34737254],
       [0.94662015, 0.54126859, 0.11476384, 0.93481717, 0.8578775 ],
       [0.33424679, 0.1003661 , 0.79871648, 0.38538724, 0.95570274],
       [0.25572254, 0.86680446, 0.1426787 , 0.16278871, 0.66711765],
       [0.8612611 , 0.60953081, 0.44476248, 0.88168337, 0.14968376]])

In [55]:
#here randn is natural rand  number  it may +ve or -ve
arr7 = np.random.randn(50)

In [57]:
arr7

array([ 0.70130382,  1.16333911, -0.55318251, -0.49220202, -2.37371652,
        0.48952666, -1.00581233,  1.8664876 ,  0.28535656,  1.04670091,
        0.80980568,  0.04017636,  0.28553811, -0.84158631,  0.04943226,
        0.69300986,  2.28365706, -0.81224954, -0.84433085, -0.46952755,
        2.61481273,  0.28316398, -0.56328942, -1.27776717,  0.63065539,
       -0.71103722, -0.96699988, -0.32298619,  0.98649568, -0.13609379,
        0.69051332,  0.69688845,  0.76058374, -0.57144644,  0.2115159 ,
        1.89474702,  0.30875815,  0.2773326 ,  1.13617617,  0.87788   ,
       -1.17739658, -0.6005593 ,  1.4306786 ,  1.48174855,  1.4374421 ,
       -1.96108081, -0.73791484,  0.2271634 ,  0.97606312, -0.31877415])

In [61]:
temp2 = arr7.reshape(10,5)

In [63]:
temp2

array([[ 0.70130382,  1.16333911, -0.55318251, -0.49220202, -2.37371652],
       [ 0.48952666, -1.00581233,  1.8664876 ,  0.28535656,  1.04670091],
       [ 0.80980568,  0.04017636,  0.28553811, -0.84158631,  0.04943226],
       [ 0.69300986,  2.28365706, -0.81224954, -0.84433085, -0.46952755],
       [ 2.61481273,  0.28316398, -0.56328942, -1.27776717,  0.63065539],
       [-0.71103722, -0.96699988, -0.32298619,  0.98649568, -0.13609379],
       [ 0.69051332,  0.69688845,  0.76058374, -0.57144644,  0.2115159 ],
       [ 1.89474702,  0.30875815,  0.2773326 ,  1.13617617,  0.87788   ],
       [-1.17739658, -0.6005593 ,  1.4306786 ,  1.48174855,  1.4374421 ],
       [-1.96108081, -0.73791484,  0.2271634 ,  0.97606312, -0.31877415]])

In [65]:
temp2.shape

(10, 5)

In [67]:
temp2.ndim

2

In [69]:
# Byusing tuples array(1,2=dim) can be generated, this tuple is converted
arr9 = np.array((4,2,4))

In [71]:
arr9

array([4, 2, 4])

In [73]:
arr9.ndim

1

In [86]:
#empty is the attribute so all the cells get zeros
arr10 = np.empty((2,3))

In [87]:
arr10

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
#tile is function to reapeating the values at 3 times
arr11 = np.tile(np.arange(3),3)

In [97]:
arr11

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [111]:
#changing the value to float by using dtype 
arr12 = np.random.rand(10)
dtype='float32'

In [112]:
arr12

array([0.85762553, 0.94977903, 0.56168686, 0.17878052, 0.77025193,
       0.49238104, 0.63125307, 0.83949792, 0.4610394 , 0.49794007])

In [117]:
arr13 = np.array(['abd','abc','saf'])

In [119]:
arr13

array(['abd', 'abc', 'saf'], dtype='<U3')

In [124]:
#here checking the type of array
arr13.dtype

dtype('<U3')

In [127]:

arr14 = np.array([True,False,True])

In [129]:
arr14.dtype

dtype('bool')

In [133]:
#numpy index and slicing
arr15 = np.arange(20)
print(arr15)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [137]:
arr15[4]

4

In [138]:
arr15[7]

7

In [140]:
#reverse indexing
arr15[-4]

16

In [142]:
arr15[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [144]:
arr15[-1:]

array([19])

In [146]:
#it start count from 0 to n-1

arr15[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [150]:
arr15[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [153]:
arr16 = np.array([[3,434,5],[4234,3424,23],[42,34,5]])

In [155]:
arr16

array([[   3,  434,    5],
       [4234, 3424,   23],
       [  42,   34,    5]])

In [157]:
arr16[0:,:]

array([[   3,  434,    5],
       [4234, 3424,   23],
       [  42,   34,    5]])

In [159]:
arr16[1,1]

3424

In [161]:
#changing the value
arr16[1,1]=15

In [163]:
arr16

array([[   3,  434,    5],
       [4234,   15,   23],
       [  42,   34,    5]])

In [165]:
arr16 = np.array([0,1,2])

In [167]:
arr16

array([0, 1, 2])

In [170]:
arr17=np.arange(7)

In [172]:
arr17

array([0, 1, 2, 3, 4, 5, 6])

In [175]:
#Arrays can be sliced using the following syntax:
arr17[1:5:2]

array([1, 3])

In [177]:
arr17[:4]

array([0, 1, 2, 3])

In [179]:
#implicity extracting the elements
arr17[4:]

array([4, 5, 6])

In [181]:
#random digit is in the form of int of the size of 3=rows and 4 coloumn
x = np.random.randint(10, size=(3, 4))

In [183]:
x

array([[6, 4, 8, 6],
       [2, 3, 1, 5],
       [2, 1, 8, 2]])

In [192]:
x[:2, :3] # two rows, three columns
x[:3, ::2] # all rows, every other column 
x[::-1, ::-1]
x[:, 0] # first column of x 
x[0, :] # first row of x 


array([6, 4, 8, 6])

In [194]:
np.random.seed(10)


In [196]:
ar=np.random.randint(0,25,10)

In [198]:
ar

array([10,  8, 22,  4, 19, 16,  4, 15, 11, 22])

In [202]:
#here we checking the number is even or not
evenMask=(ar%2==0)


In [203]:
evenMask

array([ True,  True,  True,  True, False,  True,  True, False, False,
        True])

In [207]:
#it shows the elements which is inside the  evenMask variable  
evenNums=ar[evenMask]

In [208]:
evenNums

array([10,  8, 22,  4, 16,  4, 22])

In [210]:
ar=np.array(['Hungary','Nigeria','Guatemala','','Poland','','Japan'])


In [212]:
ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='<U9')

In [214]:
ar[ar=='']='USA' ### the missing value '' is replaced by 'USA'


In [216]:
ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='<U9')

In [218]:
ar=np.arange(15)


In [220]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [229]:
#it creates the integer in reverse order
array2=np.arange(0,-10,-1)[::-1]

In [230]:
array2

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [232]:
ar=np.arange(0,7)*5


In [234]:
ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [236]:
ar=np.arange(5) ** 4


In [238]:
ar

array([  0,   1,  16,  81, 256], dtype=int32)

In [240]:
ar**4

array([       0,        1,    65536, 43046721,        0], dtype=int32)

In [242]:
ar1 = np.arange(6)**0.4

In [244]:
ar1

array([0.        , 1.        , 1.31950791, 1.55184557, 1.74110113,
       1.90365394])

In [246]:
ar=3+np.arange(0, 30,3)

In [248]:
ar

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [2]:
ar2 = np.arange(1,11)

NameError: name 'np' is not defined

In [5]:
import numpy as np

###### 

In [8]:
array6 = np.range(1,11)

AttributeError: module 'numpy' has no attribute 'range'

In [10]:
ar11 = np.arange(1,11)

In [12]:
ar11 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
ar22 = np.arange(1,11)

In [16]:
ar22

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#addition , multiplication, division, mean,std, sin cos...

In [19]:
ar11+ar22

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
ar11/ar22

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
ar11*ar22

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [25]:
np.mean(ar11)

5.5

In [27]:
np.std(ar11)

2.8722813232690143

In [29]:
np.sin(ar11)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [31]:
np.cos(ar11)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [33]:
#compering ar11 and ar22 elements
ar11<ar22

array([False, False, False, False, False, False, False, False, False,
       False])

In [35]:
ar11==ar22

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [37]:
ar11<=ar22

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [41]:
ar12 = np.array([np.pi,np.pi/2])

In [43]:
ar12

array([3.14159265, 1.57079633])

In [45]:
ar10 = np.arange(20)

In [47]:
ar10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
ar10.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
ar09 = np.arange(70)

In [54]:
ar09

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [56]:
ar09.reshape(10,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69]])

In [58]:
ar10 * ar09

ValueError: operands could not be broadcast together with shapes (20,) (70,) 

In [60]:
ar10 + ar09

ValueError: operands could not be broadcast together with shapes (20,) (70,) 

In [62]:
ar10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
ar90 = ar10.reshape(4,5)

In [66]:
ar90

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
#transpose of matrix
ar90.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [74]:
#byusing range numbers we can genatre the array
ar89 = np.array([np.arange(10),np.arange(19)])

In [76]:
ar89

array([array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])], dtype=object)

In [79]:
ar90

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
ar90.ravel

<function ndarray.ravel>

In [84]:
ar90.T.ravel

<function ndarray.ravel>

In [96]:
ar90.resize((8,))

ValueError: cannot resize this array: it does not own its data

In [99]:
array6 = np.arange(1,11)

In [103]:
ar10.resize((6,))


ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [105]:
ar=np.array([14,15,16])


In [107]:
ar

array([14, 15, 16])

In [109]:
#newaxis it will change elements interchange  thier postions
ar=ar[:, np.newaxis]


In [111]:
ar

array([[[14]],

       [[15]],

       [[16]]])

In [113]:
ar.shape


(3, 1, 1)

In [115]:
ar=np.array([[3,2],[10,-1]])


In [117]:
ar

array([[ 3,  2],
       [10, -1]])

In [119]:
#sorting the values
ar.sort(axis=1)  ###along the y-axis


In [121]:
ar

array([[ 2,  3],
       [-1, 10]])

In [123]:
ar=np.array([[3,2],[10,-1]])
ar
ar.sort(axis=0)  ###along the x-axis
ar


array([[ 3, -1],
       [10,  2]])

In [125]:
np.max(ar10)

19

In [127]:
np.min(ar10)

0

In [129]:
np.argmin(ar10)

0

In [132]:
np.argmax(ar)

2

In [134]:
ar10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [136]:
ar90

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.argmax(ar90)

In [ ]:
pwd